version: '3'

services:
  rails:
    container_name: sardines-rails
    build:
      dockerfile: docker/development/Dockerfile
      context: .
    image: sardines_rails
    volumes:
      - .:/project
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mailhog

  postgres:
    container_name: sardines-postgres
    image: postgres
    environment:
      POSTGRES_USER: sardines
      POSTGRES_PASSWORD: sardines
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    container_name: sardines-mailhog
    image: mailhog/mailhog

volumes:
  postgres_data: