version: '3'

services:
  web:
    container_name: sardines-web
    build:
      dockerfile: docker/development/dockerfile
      context: .
    image: sardines_web
    user: sardines
    volumes:
      - .:/project
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - mailhog

  postgres:
    container_name: sardines-postgres
    image: postgres
    environment:
      POSTGRES_USER: sardines
      POSTGRES_PASSWORD: sardines
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mailhog:
    container_name: sardines-mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data: