default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "sardines") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "sardines") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "sardines_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "sardines_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "sardines_production") %>
